version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: caster
    ports:
      - "9000:9000"
      - "587:587"
    environment:
      - "EMAIL_PASSWORD=<app_password>"


